### ISSUE TITLE
SharePoint Online server returns "The remote server returned an error: (403) Forbidden."

### ISSUE THREAD

**Issue by kristianoftedal** [sharepoint-sherpa/sherpa#24]
Hi!
Ive started to use Sherpa lately on my tenant, when a couple of days ago the the server started returning 403 and specifically: X-MSDAVEXT_Error: 917656; Access denied. Before opening files in this location%2c you must first browse to the web site and select the option to login automatically.

Could you please look into it?

**Comment by tarjeieo** [comment]
Microsoft has released a change to Office 365 that affects how Sherpa uploads sandboxed solutions. The workaround is to upload the package manually.

**Comment by kristianoftedal** [comment]
Ok thanks :)

**Comment by kristianoftedal** [comment]
my colleague helped me solve this with the following revamp of the method      UploadFileToSharePointOnline

/// <summary>
        /// Actually uploads the package to the library
        /// Starting point: http://sharepointfieldnotes.blogspot.fi/2014/07/uploading-large-documents-into.html
        /// </summary>
        /// <param name="context"></param>
        /// <param name="fileUrl"></param>
        /// <param name="localPath"></param>
        private void UploadFileToSharePointOnline(ClientContext context, string fileUrl, string localPath)
        {

            context.RequestTimeout = 1000000;
            context.Credentials = _credentials;
            var siteAssetsLibrary = context.Web.Lists.EnsureSiteAssetsLibrary();
            using (FileStream fs = new FileStream(localPath, FileMode.Open))
            {
                FileCreationInformation flciNewFile = new FileCreationInformation();
                flciNewFile.ContentStream = fs;
                flciNewFile.Url = Path.GetFileName(fileUrl);
                flciNewFile.Overwrite = true;
                Microsoft.SharePoint.Client.File uploadFile = siteAssetsLibrary.RootFolder.Files.Add(flciNewFile);
                context.Load(uploadFile);
                context.ExecuteQuery();
            }
        }

**Comment by tarjeieo** [comment]
Cool - I know we tried to go down that path earlier, but at that time that method did not work with sandboxed solutions. Thanks for the contribution, I tested it here and it works. We get rid of unnecessary ugly manual cookiefixing while doing it as well. Will push a new version with this fix today.
